export const FETCH_USER_INFO_START = 'FETCH_USER_INFO_START';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAIL = 'FETCH_USER_INFO_FAIL';

export const UPDATE_USER_INFO_START = 'UPDATE_USER_INFO_START';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';

export const FETCH_USER_PURCHASES_START = 'FETCH_USER_PURCHASES_START';
export const FETCH_USER_PURCHASES_SUCCESS = 'FETCH_USER_PURCHASES_SUCCESS';
export const FETCH_USER_PURCHASES_FAIL = 'FETCH_USER_PURCHASES_FAIL';

export const FETCH_USER_POINTS_START = 'FETCH_USER_POINTS_START';
export const FETCH_USER_POINTS_SUCCESS = 'FETCH_USER_POINTS_SUCCESS';
export const FETCH_USER_POINTS_FAIL = 'FETCH_USER_POINTS_FAIL';
